language: ruby
env: DB=postgres
sudo: false
cache: bundler
script: "bundle exec rake travis"
bundler_args: "--without 'development production'"
before_script:
  - "cp config/database.travisci.yml config/database.yml"
  - "psql -c 'create database dianewillis_test;' -U postgres >/dev/null"
